export const ACTIVATE_LOADING = 'ACTIVATE_LOADING';
export const ACTIVATE_TYPE_OF_DISH_LOADING = 'ACTIVATE_TYPE_OF_DISH_LOADING';
export const ACTIVATE_TYPE_OF_FOOD_INTAKES_LOADING = 'ACTIVATE_TYPE_OF_FOOD_INTAKES_LOADING';
export const ACTIVATE_ALL_DISHES_LOADING = 'ACTIVATE_ALL_DISHES_LOADING';
export const ACTIVATE_ARCHIVE_LOADING = 'ACTIVATE_ACRCHIVE_LOADING';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_DICT_TYPE_OF_DISH = 'SET_DICT_TYPE_OF_DISH';
export const SET_DICT_TYPE_OF_FOOD_INTAKE = 'SET_DICTS_DATA';
export const SET_ALL_DISHES = 'SET_ALL_DISHES';
export const SET_ARCHIVE_DATA = 'SET_ARCHIVE_DATA';
export const SET_AUTH = 'SET_AUTH';
export const SET_SELECTED_GLOBAL_MENU = 'SET_SELECTED_GLOBAL_MENU';

export const ERROR = 'ERROR';
