export const ACTIVATE_LOADING = 'ACTIVATE_LOADING';
export const ACTIVATE_TYPE_OF_DISH_LOADING = "ACTIVATE_TYPE_OF_DISH_LOADING";
export const ACTIVATE_TYPE_OF_FOOD_INTAKES_LOADING = "ACTIVATE_TYPE_OF_FOOD_INTAKES_LOADING";
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_DICT_TYPE_OF_DISH = "SET_DICT_TYPE_OF_DISH";
export const SET_DICT_TYPE_OF_FOOD_INTAKE = "SET_DICTS_DATA";
export const ERROR = 'ERROR';