export const ACTIVATE_USER_LOADING = 'ACTIVATE_USER_LOADING';
export const ACTIVATE_NEWS_LOADING = 'ACTIVATE_NEWS_LOADING';
export const ACTIVATE_CONTACTS_LOADING = 'ACTIVATE_CONTACTS_LOADING';
export const ACTIVATE_ABOUT_LOADING = 'ACTIVATE_ABOUT_LOADING';
export const ACTIVATE_MENTIONS_LOADING = 'ACTIVATE_MENTIONS_LOADING';
export const ACTIVATE_PHOTOALBUM_LOADING = 'ACTIVATE_PHOTOALBUM_LOADING';
export const ACTIVATE_CONDTITONS_LOADING = 'ACTIVATE_CONDTITONS_LOADING';
export const ACTIVATE_TEACHERS_LOADING = 'ACTIVATE_TEACHERS_LOADING';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_NEWS_DATA = 'SET_NEWS_DATA';
export const SET_NEWS_TARGET_DATA = 'SET_NEWS_TARGET_DATA';
export const SET_CONTACTS_DATA = 'SET_CONTACTS_DATA';
export const SET_ABOUT_DATA = 'SET_ABOUT_DATA';
export const SET_MENTIONS_DATA = 'SET_MENTIONS_DATA';
export const SET_PHOTOALBUM_DATA = 'SET_PHOTOALBUM_DATA';
export const SET_CONDITIONS_DATA = 'SET_CONDITIONS_DATA';
export const SET_TEACHERS_DATA = 'SET_TEACHERS_DATA';
export const SET_AUTH = 'SET_AUTH';

export const ERROR = 'ERROR';
